application: yasai-check
version: 1
runtime: python27
api_version: 1
threadsafe: true

libraries:
- name: jinja2
  version: latest 

handlers:
- url: /favicon.ico
  static_files: static/favicon.ico
  upload: static/favicon.ico
- url: /style.css
  static_files: static/style.css
  upload: static/style.css
- url: /signup
  script: signup.app
- url: /additem
  script: additem.app





- url: /(.*)
  script: mainpage.app

